Allow 32bits build
LagFreeGames/libelf-lfg-win32 pull request #1
Opened 2021-06-13 10:44 UTC by xantares

2021-06-13 11:35 UTC, jpark37 requested changes

2021-06-13 11:35 UTC, jpark37 commented on contrib/elftoolchain/libelf/_libelf_config.h
> +#endif
How about this?
```
#ifdef _WIN32

#if	defined(_M_X64)

#define	LIBELF_ARCH		EM_X86_64
#define	LIBELF_BYTEORDER	ELFDATA2LSB
#define	LIBELF_CLASS		ELFCLASS64

#elif	defined(_M_IX86)

#define	LIBELF_ARCH		EM_386
#define	LIBELF_BYTEORDER	ELFDATA2LSB
#define	LIBELF_CLASS		ELFCLASS32

#else
#error	Unknown Windows architecture.
#endif
#endif  /* _WIN32 */
```

2021-06-13 11:40 UTC, jpark37 commented
Can you update the description? What is this for? Do you really need to use ELF? My impression is that the Mesa maintainers would like to rid themselves of this dependency.

2021-06-13 14:19 UTC, xantares commented
I dont know whats its actually used for, but they did not remove it yet.

2021-06-13 14:56 UTC, jpark37 commented
I have added a description template to the PR. Please fill it out if you want me to merge the changes.

2021-06-14 00:33 UTC, jpark37 commented
What are your Mesa Meson build arguments?

2021-06-14 07:00 UTC, xantares commented
I enabled the amd vulkan driver

2021-06-14 07:19 UTC, jpark37 commented
Okay, I'm closing the PR.

If anyone related to RADV has a need to build the driver for 32-bit Windows, then I'll reconsider. I'm not interested in testing and merging PRs for this library unless they serve Mesa in some useful way.

2021-06-14 07:19 UTC, closed without merging

2021-06-14 07:23 UTC, xantares commented
how that's not what I'm doing ?
please reconsider